assistant_accountant/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.index, name='index')
]

assistant_accountant/assistant_accountant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

assistant_accountant/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('yandex-direct-callback',
         views.yandex_direct_callback,
         name='yandex_direct_callback'),
    path('vk-callback', views.vk_callback),
    path('yandex-direct/test/', views.yandex_test, name='yandex_test'),
    path('vk/test/', views.vk_test, name='vk_test'),
    path('my-target/auth', views.my_target_auth, name='my_target_auth'),
    path('my-target/test', views.my_target_test, name='my_target_test'),
    path('sheet', views.sheets_view, name='sheets_view'),
    path('test', views.test)
]

assistant_accountant/about/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'about/index.html', context)

assistant_accountant/templates/about/index.html
{% extends 'base.html' %}
{% block title %} Стартовая страница {% endblock %}
{% block content %}
  <div class="row">
    <div class="col-12">
      {% with request.resolver_match.view_name as view_name %}
        <p><a href="{% url 'dashboard:index' %}">dashboard:index</a></p>
        <p><a href="{% url 'dashboard:yandex_test' %}">dashboard:yandex_test</a></p>
        <p><a href="{% url 'dashboard:vk_test' %}">dashboard:vk_test</a></p>
        <p><a href="{% url 'dashboard:my_target_auth' %}">dashboard:my_target_auth</a></p>
        <p><a href="{% url 'dashboard:my_target_test' %}">dashboard:my_target_test</a></p>
        <p><a href="{% url 'dashboard:sheets_view' %}">sheets_view</a></p>
      {% endwith %}
    </div>
  </div>
{% endblock %}